In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split

# NOTE: Make sure that the class is labeled 'target' in the data file
tpot_data = pd.read_csv('train.csv')
ids = tpot_data['ID_code']
target = tpot_data['target']
tpot_data.drop(columns=['ID_code'], inplace=True)
tpot_data.drop(columns=['target'], inplace=True)

training_features, testing_features, training_target, testing_target = \
            train_test_split(tpot_data, target.values, random_state=42)

In [2]:
training_features

var_0   var_1    var_2    var_3    var_4    var_5   var_6    var_7  \
21743    8.7992  4.8752  11.8703   7.6905  11.7383  -9.2393  5.0377   9.9358   
124554  12.9898 -3.6631   9.6294   5.9422  11.6071 -13.2940  5.6818  17.7083   
10351   12.8229  3.4702   5.2420   8.0014  10.6487  -2.2849  5.7165  16.2296   
135164  13.9625 -4.1899  10.4708   5.7792  11.7436 -10.1196  5.3161  19.4508   
49969    6.8356  1.5991  13.2605   6.6857  11.7398  -0.0347  5.3015  17.8723   
47120   10.0797  2.7717  15.7968   4.8702  10.8181  -2.3863  5.4396   9.9311   
4249    13.7070  1.1814   8.1664   5.1509  10.2251  -4.8527  5.2448  16.1194   
59266    8.6460 -0.5916   8.3863   1.8604   8.2738  -9.9528  5.9704  20.8244   
32546    7.3753  0.4056   9.3808   2.6689  12.6992  -3.8742  4.5431  21.8422   
74977   14.3264 -3.2413   9.4960   5.5032  11.1821  -3.2128  3.9634  18.8645   
186421  11.1958  4.7661  10.4065   6.6542   9.4425  -6.8538  5.9565  18.6141   
42641    8.5857 -5.0036  11.8131   5.2858   8.7745  -7.4387  6.9681  22.6371   
110066   7.9797 -6.1163   5.9513   8.6175  10.6742  -1.8840  4.2030  12.0620   
165551  17.2467 -2.8219  13.2589  10.4861  11.8744  -5.6172  6.1077  15.4644   
128440  14.0797  4.1398  14.9020   9.9631   8.8926  -0.2195  6.2840  15.8100   
56463   18.2304 -3.0074   8.9956   6.7127   9.2928  -0.1916  4.4998  14.8161   
130932   9.1710 -3.5902  11.5339   8.3837  12.6720   1.7551  4.3242  22.2599   
26836   12.0053  0.4250  13.1806   4.9699  10.1555 -18.0689  3.6876  17.2930   
107131  13.0836 -0.2853  16.8427   6.4832  12.1872   3.5270  6.3779  16.0235   
85069   11.4203 -9.4780  13.5567   5.4408  12.0340  12.8987  6.0972  10.0259   
52490   12.9530 -7.6792  12.3957   9.5194  12.7400  -9.5719  5.9660  19.2038   
101446  16.3280 -5.5847   9.5069   8.6728  14.6506   2.0236  4.3012  22.0153   
116142  18.9784 -1.4045   8.8122   7.3165  11.3949 -11.4177  4.6929  12.5989   
85792   14.4130  2.0693   9.8559   9.7598  11.5596  -6.5532  7.4412  14.1884   
142755  12.9831  0.6940   8.7624   5.0942  14.2122   2.1249  6.1329  16.7920   
103695  10.4424 -6.3032   7.3913   6.9752   7.9903 -11.0313  7.0656  13.3108   
32253   12.2801 -6.5565  10.0688   7.6760  10.3356 -16.0754  4.1053  13.6908   
198632   8.6077 -4.9305   7.6907   9.3895   8.0567  -4.0672  4.6344  14.4253   
140531  10.2163 -0.9071   5.8164   6.1217  11.9344 -10.5872  4.9276  13.4879   
140882  13.3716 -4.4462   7.6760   6.5988  12.9123  -2.9685  4.7438  17.6899   
...         ...     ...      ...      ...      ...      ...     ...      ...   
156730   8.6902 -5.9632   9.4429   6.7394  10.8351   3.1708  3.7936  18.9185   
130608  12.4530  0.3766  11.5032   9.6151  12.8622 -11.2307  6.1531  18.7359   
159765   8.0867  0.6868  13.6995   9.4850  10.6324 -15.4100  4.8195  16.3852   
85305   13.0528 -5.7261  11.4936   6.2353  10.6649 -13.2971  5.4777  15.9482   
184779  16.3305  2.0590   7.8542   8.6445  10.8511  -4.5080  5.3797  21.2407   
103355  16.2478 -1.2022  12.5715   6.6322  13.6026   2.0089  4.5118  20.9909   
5311    13.6765 -3.4317   7.4307   5.5158  10.6813 -12.3122  4.6143  19.5227   
199041   6.8000  0.0966   9.0483   9.8033   9.2290 -10.3801  7.4430  16.7564   
64925    8.7056 -3.8304  10.1277   7.9692  11.0533  -8.9682  5.6584  13.7656   
194027  11.7439  5.4209  11.7732   8.6499  13.7139   4.4620  5.3061   9.8367   
59735   12.2455 -5.8503   7.2606   5.6580  12.0105 -14.4159  5.8096  20.9937   
769     10.4436 -4.5353  13.2833  10.6446  11.1138 -11.2362  6.2879  21.8474   
64820    8.5138 -7.2189  10.6652   3.0392   8.2097   0.4025  4.5748  16.8696   
67221    8.8009 -4.3238  17.7898   6.1764  11.6160  -2.9058  5.0792  13.7550   
41090   13.9853 -6.9652   8.6203   5.0795  11.0138  -4.6746  5.8757  16.6488   
16023   13.3079 -5.7326  10.6380   8.1817  11.1339  -5.7439  4.0670  11.3690   
191335   7.7407  2.8590   7.1075   6.6993  10.7365  -6.2643  4.1604  15.9989   
175203   9.7292  2.1664   7.3127   8.0715   9.9782 -12.3708  4.5569  20.5761   
126324  18

In [3]:
training_target

array([0, 0, 0, ..., 0, 0, 0])

In [4]:
testing_features

var_0    var_1    var_2    var_3    var_4    var_5   var_6    var_7  \
119737  11.0038  -4.5026   9.0662   6.4313  10.7061 -15.2857  5.1233  16.7875   
72272   12.8473  -6.1848   6.8799   2.0164  12.7998  10.2781  4.4191  15.6940   
158154  13.1827  -0.8344  13.4689   3.9060  13.5984   4.6475  5.9659  24.0557   
65426    8.2132   1.2309  11.1464   9.4524  10.2142   4.0416  5.3989  20.4527   
30074    5.5681   4.6355  15.2350   3.0718  11.8178 -15.0502  3.8357  12.0169   
23677   10.9255  -1.9087  10.4506   8.4906  12.2991 -15.5323  4.2468  13.7538   
134858  11.4503   4.0273   8.9075   8.0067   9.4094   0.3297  5.6029  12.6545   
176418  11.8280  -2.4992  10.7057   8.6949  14.1530 -13.5919  5.4506  12.5229   
132467  12.9107  -2.8342   8.8888  11.0043   8.0937  -7.1183  4.8870  10.1669   
4082    10.1393  -1.1543   7.9994   4.8873  14.2020   0.1650  4.5320  16.0232   
74456   12.0218   3.3372  13.8376  11.2463  10.6005  -1.3874  6.8155  12.6782   
142133  15.4835  -1.8547  11.3827  10.4096  11.1630   2.7109  6.2256  21.0018   
186433   8.5120  -4.6407   8.9969   5.8765  12.7624  -3.7790  7.7360  12.0749   
84660   12.5949  -6.3488   9.8330   5.4106  12.2621   0.9149  6.7641  18.3219   
117167  12.0373  -3.8934   7.0296   7.6874  13.1976  -6.0295  5.7953  12.4830   
110852  10.0662   1.2406   8.5874   3.3651  12.2217  -4.5245  6.0293  21.8215   
105000   7.7176  -2.7919  12.9485   5.9233   8.1852 -19.3043  4.9315  19.7475   
181463  12.5213  -0.4913   9.1759   7.5670  12.8713 -12.0395  3.9470  13.0598   
9447     6.4936  -0.4557  13.9954   8.3852   9.2858  -8.2315  4.6136  11.7233   
178531   8.2947   5.3051   8.1802  10.6153  11.0781 -10.3283  5.4261  17.4832   
168258  11.2985   4.7131   5.9156   5.4387  10.0909  -7.6092  4.6024  19.9475   
30068   13.2496  -3.9807   9.1212   7.3016  13.4618 -18.5453  5.6490  18.4605   
28455   10.7609   2.8025  13.0133   4.8259   8.9175 -15.3828  5.5276  13.7156   
156518  10.2380  -4.9915   8.0838   5.4247   9.0290   3.7216  6.0249  18.9337   
7816    10.4574  -5.1531   8.5583   6.9137  14.2766  -2.2728  6.6592  14.3851   
5254     8.8637  -2.7066   8.1360   7.0380  12.2143 -10.2819  5.8064  16.9007   
9848    11.3537   0.7457  12.0122   8.6068  12.6483  -1.0550  6.6239  20.7108   
130690  11.5860   7.0546  10.8911   4.6965   8.9340 -13.4323  6.4969  12.3853   
191766   7.0682  -4.5855   8.1524   8.0415  10.2232  -1.5471  6.4201  21.0255   
48710   16.1922   0.2401  12.5954   6.5594  10.0859  -0.1612  5.8131  17.5410   
...         ...      ...      ...      ...      ...      ...     ...      ...   
5924     7.3824  -4.2187   8.9068   4.3773  12.1268 -15.8812  5.9201  21.5027   
71319    5.4441   1.2408  10.8458   4.7798  12.3768 -13.3041  6.0166  16.8781   
2486    11.7953  -3.5043  10.8502   6.0237  10.6847  -4.2237  6.3395  14.3793   
179651  11.9247   4.2370   8.4986   6.6290   8.5053  -5.4237  6.0543  17.2189   
118468   8.1939  -4.5376   7.9892   5.3522  13.1775  -1.0093  5.6561  20.9859   
7520    13.6212  -0.3577   9.1526   3.5152  10.8645 -16.2018  6.4238  10.4206   
144286  10.2681   0.8198  11.6389   7.7323  10.2197 -10.8923  7.1201  15.5957   
191598  10.6783  -2.4001  13.8210   6.5402   9.7622   1.5768  5.4509  15.5590   
129929   8.7160  -2.2433  13.8181   8.2087   8.1869  13.5740  5.0164  18.1834   
68142    8.1805   3.4732  14.4664   5.1596  10.6354 -11.3766  5.3242  13.7299   
96685    9.1314   3.3112  12.9884   8.6144  12.2302   6.9218  5.8248  15.4449   
112513  13.6382   3.3764  12.1141   6.6586  12.6302   7.2577  5.4935  19.7958   
147837  10.9062  -0.7185  15.7813   4.0567   9.3991  -8.2580  6.6670  12.4750   
75199   12.4045  -1.6994   6.1059   9.3265  11.1205   5.2090  7.2625  19.3283   
109766  13.4509  -5.4021   6.5304   5.1845  13.1351   4.3593  5.2054  19.9237   
31329    9.9992  -3.6372   9.1145   9.7920   9.1940   7.2334  4.4861  22.4319   
130716  10.8720  -1.1133   9.3146   7.5160  12.1913 -11.2699  5.3866  12.9582   
17989    7.7428   1.2374  10.6865   5.492

In [5]:
testing_target

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
# Replace this cell with your model. Save the target predictions in an array called 'results'
import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline, make_union
from tpot.builtins import StackingEstimator, ZeroCount

# Average CV score on the training set was:0.920530303030303
exported_pipeline = make_pipeline(
    StackingEstimator(estimator=GaussianNB()),
    VarianceThreshold(threshold=0.001),
    ZeroCount(),
    ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.15000000000000002, min_samples_leaf=6, min_samples_split=2, n_estimators=100)
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [7]:
results

array([0, 0, 0, ..., 0, 0, 0])

In [8]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [15]:
precision_score(testing_target, results) #, average='micro'

0.7157612853863811

In [16]:
recall_score(testing_target, results)

0.3654296875

In [17]:
f1_score(testing_target, results)

0.48383760020687866