In [4]:
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split

# NOTE: Make sure that the class is labeled 'target' in the data file
tpot_data = pd.read_csv('train_trimmed.csv')
ids = tpot_data['ID_code']
target = tpot_data['target']
tpot_data.drop(columns=['ID_code'], inplace=True)
tpot_data.drop(columns=['target'], inplace=True)

training_features, testing_features, training_target, testing_target = \
            train_test_split(tpot_data, target.values, random_state=42)

In [5]:
training_features

var_0   var_1    var_2   var_3    var_4    var_5   var_6    var_7  \
14  14.3688 -6.6356  14.2966  6.9261  11.1505 -16.9995  4.7413  18.8685   
8    6.8348 -4.5316   9.8671  7.5185   9.4721  -8.6485  4.9690  14.1903   
13  13.2790  3.3209  11.7434  8.9755  12.0563   7.2586  4.7792  14.1848   
2    6.3322  2.6947  12.2870  7.4429  12.7399  -9.9160  5.3338  20.5643   
9    8.6866 -3.5418  11.5416  9.0093   8.8574  -8.0907  5.5387  18.0916   
16  15.9808  2.8589  16.5100  4.5528  14.7661 -15.8659  5.7522  14.9275   
4   12.6075  2.4927   8.9884  9.6498  14.5220  -7.8886  6.3709  17.8214   
7   14.4317 -3.0107  13.1385  6.4003  10.3763  -6.0135  4.9410  12.7321   
10  18.1066  4.7263   9.2329  9.0609  13.0213  -7.3595  5.5344  12.2545   
12   6.6413 -5.4186  10.3750  4.5820  12.0450  -0.2831  5.2098  11.4290   
3   12.5130 -7.3175   9.4896  7.2075  13.3605  -4.1300  3.6747  16.3560   
6    7.5464 -6.5252  17.8344  9.8055  11.4954   1.5933  5.8547  17.1240   

     var_8   var_9   ...     var_190  var_191  var_192  var_193  var_194  \
14  0.1699  5.4457   ...      0.8008   2.7644   0.3291  -1.8340  20.2584   
8  -0.8247  5.0298   ...      9.7644   3.5653   2.6485   3.5409  21.2522   
13 -4.1768  8.5771   ...      0.8341   3.6234   2.9552   2.5220  20.5220   
2  -3.3393  8.8550   ...      4.3357   8.4897   1.3065   3.9099  12.1361   
9  -1.7200  7.1921   ...     13.2313   7.5801   2.4395   7.0097  20.1328   
16  4.4025  6.4932   ...      9.4278   6.5868  -0.4148   3.0314  18.6745   
4   3.8247  6.7141   ...      3.7570   7.9989  -0.5040  10.8319  20.9614   
7   0.7437  8.9411   ...     -4.4343   2.8202   1.8824   7.9774  11.2699   
10  6.6798  5.4763   ...      7.8296   6.9695   4.8329   2.1466  19.3861   
12  4.7959  7.2960   ...      8.2347   8.6634   2.4581  -3.2121  19.1581   
3   1.2980  7.4382   ...      3.5755  10.6708   2.2302   3.0759  13.6795   
6   1.0084  8.2994   ...      1.7126   8.2453  -0.7580   5.4785  18.8941   

    var_195  var_196  var_197  var_198  var_199  
14  -0.6278  -0.3616  10.0631  10.7028  -7.1885  
8    1.6589  -1.9107   9.5588  15.8586  15.0897  
13   2.5515   4.4347   7.7101  14.0678   8.2117  
2    0.1458   7.4042   8.7478  12.5399   1.2690  
9    0.5190  -5.5820   9.9177  13.7349   3.2101  
16  -1.4999  -2.2192  10.1525   8.1803  -8.2026  
4    1.5378   2.0791   9.5825  14.4589   9.8037  
7    0.3099  -0.6810   8.6662  19.6868   1.5335  
10  -0.9523  -0.6711   7.9997  19.8298  10.8274  
12   0.2439   9.0800   8.9653  18.0447  -8.2539  
3   -2.7628   2.9280   8.7245  13.9159  -9.3303  
6    0.9059   7.2603   8.2095  16.4703   3.3198  

[12 rows x 200 columns]

In [7]:
training_target

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [6]:
testing_features

var_0   var_1    var_2    var_3    var_4    var_5   var_6    var_7  \
0    6.8488  7.4361  12.1328   7.0229  10.6453   6.2779  5.5375  12.1812   
1   18.7685 -7.3518  14.3081   7.0872   9.8062  -9.6050  5.7641  13.2822   
5   12.4235  7.9335  16.5343  10.0168  12.0363  -8.2683  4.5916  14.7026   
15   7.4808 -6.1076   8.3039   9.2932   9.8268 -11.0138  4.6876  15.9432   
11   9.0139 -6.8424   9.7420   8.6105  14.4030  -9.0778  6.1839  18.7792   

     var_8   var_9   ...     var_190  var_191  var_192  var_193  var_194  \
0   5.9043  4.7539   ...      6.3761   5.6435   0.4286   2.8341  13.3522   
1   2.8915  7.3591   ...     -1.2127   7.8807   3.0221   5.3729  16.9720   
5   4.5243  6.2118   ...     -2.8397   4.2402   2.2599   2.4817  14.7967   
15  0.0054  8.7960   ...      1.0987  12.4365   2.1108   5.8730  15.6310   
11 -2.3936  7.7564   ...      9.5754   7.8368  -0.0010  -2.2252  16.0935   

    var_195  var_196  var_197  var_198  var_199  
0   -0.6135   8.6763   8.2321   8.5844  -7.2585  
1    0.0521   9.1714  10.0606  20.1927 -25.6338  
5    1.1954  -7.8816  10.7882  20.0428  13.8621  
15  -1.3646  -0.3934  10.1977  14.5103  12.2519  
11  -1.2212  -4.2278   8.9434  21.5017 -13.3040  

[5 rows x 200 columns]

In [8]:
testing_target

array([1, 0, 1, 0, 1])

In [9]:
# Replace this cell with your model. Save the target predictions in an array called 'results'
exported_pipeline = GradientBoostingClassifier(learning_rate=0.5, max_depth=4, max_features=0.05, min_samples_leaf=8, min_samples_split=12, n_estimators=100, subsample=0.9500000000000001)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

In [10]:
results

array([0, 0, 0, 0, 0])

In [35]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [39]:
precision_score(testing_target, results) #, average='micro'

0.0

In [40]:
recall_score(testing_target, results)

0.0

In [41]:
f1_score(testing_target, results)

/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


0.0